server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/customer/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/product/**
        - id: service-bill
          uri: lb://service-bill
          predicates:
            - Path=/bill/**