server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: lb://service-customer
          predicates:
            - Path=/customer/**
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/product/**
        - id: service-bill
          uri: lb://service-bill
          predicates:
            - Path=/bill/**
        - id: service-acquisition
          uri: lb://service-acquisition
          predicates:
            - Path=/acquisition/**
        - id: service-credit
          uri: lb://service-credit
          predicates:
            - Path=/credit/**
        - id: service-card
          uri: lb://service-card
          predicates:
            - Path=/card/**

