server:
  port: 8099

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-customer
          uri: http://localhost:8081/
          predicates:
            - Path=/customer/**
        - id: service-product
          uri: http://localhost:8083/
          predicates:
            - Path=/product-bank-jp/**
        - id: SERVICE-ACQUISITION
          uri: http://localhost:8087/
          predicates:
            - Path=/acquisition/**