eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8086
spring:
  application:
    name: service-deposit
  data:
    mongodb:
      database: DB-Bank
      uri: mongodb://ambootcampdemo:PWUjMr10NYFaFCVXZ7QjGNlEFJCNWw1zsdmATF35LE1LZyHGvZvEajWn3WpAwXYEJ7yIGZDZgWHkvzmKznnQqA==@ambootcampdemo.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@ambootcampdemo@