eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8088
spring:
  application:
    name: service-debit
  data:
    mongodb:
      uri: mongodb://localhost:27017/DB-Bank