eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8095
spring:
  application:
    name: service-card
  data:
    mongodb:
      uri: mongodb://localhost:27017/DB-Bank